### ISSUE TITLE
Frontmatter parsing error

### ISSUE THREAD

**Issue by sugan-reden** [irskep/djockey#55]
Hi, I've been starting to make some tests to transfer a project into Djockey, but hit roadblock at the start with the frontmatter.

My current test consists simply of

```
japanese-learning_djockey/
└── docs/
    ├── src/
    │   ├── index.dj
    │   └── test-doc.dj
    ├── output
    └── djockey.yaml
```

and inside the `test-doc.dj` file I've written:

```markdown
---
title: "A Custom Title"
---

# A test title

...
```

But, this still results in
![image](https://github.com/user-attachments/assets/0aa4f598-5153-4067-93a6-c3f7b4f74e7b)

I've tried searching for a bit, but couldn't pin down what exactly could be the issue, or what mistake I may have made.

May I ask if you would have a idea or an inkling as to what went wrong?

**Comment by irskep** [comment]
Would you be open to creating a git repo with the exact file contents? I don't spot any errors. The front matter is parsed separately from the markup language, so djot or md or whatever shouldn't matter.

You are probably the first user who isn't me, so I hope I can get you through any papercuts quickly and fix them for others.

**Comment by irskep** [comment]
On my machine, I wrote this djockey.yaml (copied from some tests):

```yaml
site_name: "E2E"
url_root: https://example.com

input_dir: src
output_dir:
  html: out/html
  gfm: out/gfm
```

And this `src/index.dj`:

```djot
---
title: "A Custom Title"
---

# A test title

...
```

And it seems to be correct:

<img width="1512" alt="Screenshot 2024-12-02 at 9 06 31 PM" src="https://github.com/user-attachments/assets/275bf292-1a76-4c11-8d3c-79dc0fd9088a">

I wonder if you're on Windows and the line breaks are different characters than on Mac or Linux? I'll look into that possibility. In the meantime, if you're on Windows, see if you can "save with UNIX line breaks," which is an option in some programs.

**Comment by irskep** [comment]
Alright, I think I fixed it. Please update to version 0.2.7 and try again. Thanks for the report!

**Comment by sugan-reden** [comment]
Hi! Thanks for the swift response ^^ And sorry I couldn't be as fast 🐌, it was already time for bed where I was at 🌃.

---

> Would you be open to creating a git repo with the exact file contents? I don't spot any errors. The front matter is parsed separately from the markup language, so djot or md or whatever shouldn't matter.

That's a good point, I hadn't gotten to uploading a repo yet since I normally use GitLab to publish content. I'll make a test GitHub one and send a link.

> You are probably the first user who isn't me, so I hope I can get you through any papercuts quickly and fix them for others.

My, I thank you for your concern ❤️. I hope this goes well too, I'm quite interested in this even though I sadly can't help much on the programming side of things.

---

> I wonder if you're on Windows and the line breaks are different characters than on Mac or Linux? I'll look into that possibility. (...)

That's a good guess, I am indeed on Windows. It's been a while since I've used Linux, but I had no idea the linebreak characters were/could be different. That kinda makes curious as to why that would be 🤔.

> In the meantime, if you're on Windows, see if you can "save with UNIX line breaks," which is an option in some programs.

Got it, I'll look into that. I've been using Neovim through pwsh to make edits, so this may take me a bit.

---

> Alright, I think I fixed it. Please update to version 0.2.7 and try again. Thanks for the report!

Will do! (T-T)7 A big thanks for this ❤️.

---

Hmm 🤔, I may have messed something up

The only thing I've done is `bun update djockey`, then tried `bunx djockey .\docs --local`. But it's throwing me the following error:

``` shell
bunx djockey .\docs --local
node:internal/modules/package_json_reader:267
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
        ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'remark-parse' imported from C:\Users\reden\node_modules\djockey\dist\input\parseFile.js
    at Object.getPackageJSONURL (node:internal/modules/package_json_reader:267:9)
    at packageResolve (node:internal/modules/esm/resolve:768:81)
    at moduleResolve (node:internal/modules/esm/resolve:854:18)
    at defaultResolve (node:internal/modules/esm/resolve:984:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:654:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:603:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:586:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:242:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:135:49) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v23.3.0
```

I don't really know where to look here, I've done a `-force` reinstall of bun & djockey, and restarting the terminal, but it's still throwing the same error. May I ask for your insight again?

**Comment by irskep** [comment]
I think I made a mistake cutting the release and accidentally included some files from the wrong branch. Please try 0.2.8, should be available now.

**Comment by sugan-reden** [comment]
Hi again!

That's alright, it happens. 🫠

> Please try 0.2.8, should be available now.

Got it 🫡. I'll try that.

**Comment by sugan-reden** [comment]
Just tried it and it works now! Big thanks for this :)
